# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
## DALEXtra imports reticulate so need to use an empty requirements.txt
## when deploying on Connect
library(DALEXtra)
library(dplyr)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(workflows)
}
b <- board_connect(auth = "envvar")
v <- vetiver_pin_read(b, "julia.silge/attrition-rf")
explainer <- pin_read(b, "julia.silge/attrition-explainer")

handler_explain <- function(req) {
    shap <- predict_parts(
        explainer = explainer,
        new_observation = req$body,
        type = "shap",
        B = 20
    )
    shap %>%
        group_by(variable) %>%
        summarize(mean_val = mean(contribution), sd_val = sd(contribution)) %>%
        arrange(mean_val)
}

#* @plumber
function(pr) {
    pr %>%
        vetiver_api(v) %>%
        pr_post(path = "/explain", handler = handler_explain)
}
