# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(LiblineaR)
    library(parsnip)
    library(recipes)
    library(textrecipes)
    library(themis)
    library(workflows)
}
b <- board_rsconnect("envvar", server = "https://colorado.rstudio.com/rsc")
v <- vetiver_pin_read(b, "julia.silge/netflix_descriptions", version = "55497")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v, debug = TRUE)
}
