# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(dials)
    library(dplyr)
    library(LiblineaR)
    library(parsnip)
    library(purrr)
    library(recipes)
    library(rlang)
    library(rsample)
    library(textrecipes)
    library(themis)
    library(tibble)
    library(tidyr)
    library(tune)
    library(vctrs)
    library(workflows)
    library(yardstick)
}
b <- board_s3(bucket = "vetiver-pubescent-akitainu")
v <- vetiver_pin_read(b, "netflix_descriptions", version = "20220309T041218Z-b73d9")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v, debug = TRUE)
}
