---
title: "Publish and version with AWS S3"
output: html_document
date: '2022-03-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Train a model

```{r}
library(tidymodels)
library(textrecipes)
library(themis)

url <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv"

netflix_types <- readr::read_csv(url) %>%
    select(type, description)

set.seed(123)
netflix_split <- netflix_types %>%
    select(type, description) %>%
    initial_split(strata = type)

netflix_train <- training(netflix_split)
netflix_test <- testing(netflix_split)

netflix_rec <- recipe(type ~ description, data = netflix_train) %>%
    step_tokenize(description) %>%
    step_tokenfilter(description, max_tokens = 1e3) %>%
    step_tfidf(description) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_smote(type)

svm_spec <- svm_linear() %>%
    set_mode("classification") %>%
    set_engine("LiblineaR")

netflix_fit <-
    workflow(netflix_rec, svm_spec) %>%
    fit(netflix_train)

```

## Create a deployable vetiver model

```{r}
library(vetiver)
v <- vetiver_model(netflix_fit, "netflix_descriptions")
v

## manually add paws.storage for now
v$metadata$required_pkgs <- c(v$metadata$required_pkgs, "paws.storage")
```

## Publish and version model on AWS S3

Before running the next code chunk, you need to authenticate to AWS. I use (in the terminal):

```
aws configure sso
```

Now in R:

```{r}
library(paws)
library(glue)
library(pins)
set.seed(1)
identifier <- glue::glue("vetiver-", ids::adjective_animal(style = "kebab"))
identifier <- as.character(identifier)
svc <- s3()
svc$create_bucket(
    Bucket = identifier,
    CreateBucketConfiguration = list(LocationConstraint = "us-east-2")
)

model_board <- board_s3(bucket = identifier)
vetiver_pin_write(model_board, v)
```


## Create API

```{r}
library(plumber)
pr() %>%
    vetiver_api(v, debug = TRUE) %>%
    pr_run(port = 8088)
```




